#!/usr/bin/env python3
"""Audit and aggregate the HotpotQA document-vector extension."""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
IN = ROOT / "results/hotpot_semantic_v1"


def main():
    rows = json.loads((IN / "raw.json").read_text())
    expected = {(s, c, p) for s in [0, 1, 2] for c in ["shifted", "shuffled"]
                for p in ["flat", "ivf_fixed", "ivf_rebuilt", "hnsw"]}
    got = {(r["seed"], r["condition"], r["policy"]) for r in rows}
    if got != expected or len(rows) != 24:
        raise ValueError(f"incomplete matrix: {len(rows)} rows")
    for r in rows:
        if len(r["events"]) != 6:
            raise ValueError("incomplete update rounds")
        if not all(e["indexed"] == 80000 + 4000 * e["round"] for e in r["events"]):
            raise ValueError("unexpected corpus checkpoint")

    budgets = {"flat": [0], "ivf_fixed": [4, 16, 64],
               "ivf_rebuilt": [4, 16, 64], "hnsw": [16, 64, 256]}
    summary = {"protocol": "hotpot-semantic-order-v1", "seeds": [0, 1, 2], "rows": 24,
               "final_vectors": 100000, "dimension": 384, "means": {}, "order_differences": {}}
    for condition in ["shifted", "shuffled"]:
        for policy, bs in budgets.items():
            for b in bs:
                values = [r["summaries"][str(b)]["recall"] for r in rows
                          if r["condition"] == condition and r["policy"] == policy]
                costs = [r["summaries"][str(b)]["service_ms"] for r in rows
                         if r["condition"] == condition and r["policy"] == policy]
                summary["means"][f"{condition}/{policy}/{b}"] = {
                    "recall": float(np.mean(values)), "service_ms": float(np.mean(costs)),
                    "recall_seed_values": [float(x) for x in values]}
    for policy, bs in budgets.items():
        for b in bs:
            a = summary["means"][f"shifted/{policy}/{b}"]["recall"]
            z = summary["means"][f"shuffled/{policy}/{b}"]["recall"]
            summary["order_differences"][f"{policy}/{b}"] = float(a - z)
    (IN / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")

    def m(c, p, b, key):
        return summary["means"][f"{c}/{p}/{b}"][key]

    lines = [
        "% Generated by scripts/analyze_hotpot_semantic.py; three seeds.",
        "\\begin{table*}[t]",
        "\\caption{HotpotQA document-semantic extension. Final corpus is 100k title-prefixed context-sentence vectors (384 dimensions), with 80k initial vectors and five 4k updates. R is mean test Recall@10 over post-update checkpoints; C is insertion, rebuild and test-query work.}",
        "\\label{tab:hotpot}", "\\centering\\scriptsize",
        "\\begin{tabular}{llrrrrr}", "\\toprule",
        "Policy & Budget & Shifted R & Shuffled R & $\\Delta R$ & Shifted C (ms) & Shuffled C (ms) \\\\", "\\midrule",
    ]
    for p, bs in budgets.items():
        for b in bs:
            budget = "--" if p == "flat" else str(b)
            delta = summary["order_differences"].get(f"{p}/{b}", 0.0)
            lines.append(f"{p.replace('_', ' ')} & {budget} & {m('shifted',p,b,'recall'):.4f} & {m('shuffled',p,b,'recall'):.4f} & {delta:+.4f} & {m('shifted',p,b,'service_ms'):.1f} & {m('shuffled',p,b,'service_ms'):.1f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    (ROOT / "paper/hotpot_semantic_table.tex").write_text("\n".join(lines))
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
