#!/usr/bin/env python3
"""Build the large-scale dynamic-index table from raw, seed-level logs."""
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "results/semantic_1m_dynamic_v3/raw.json"
OUT = ROOT / "paper/large_scale_dynamic_table.tex"


def fmt(v, digits=1):
    return f"{v:.{digits}f}"


def main():
    rows = json.loads(INPUT.read_text())
    groups = defaultdict(list)
    for r in rows:
        s = r["summaries"]["0.95"]
        groups[(r["condition"], r["policy"])].append((r, s))
    names = {"ivf_fixed": "IVF-fixed", "ivf_rebuilt": "IVF-rebuilt", "hnsw": "HNSW"}
    order = ["shifted", "shuffled"]
    policies = ["ivf_fixed", "ivf_rebuilt", "hnsw"]
    lines = [
        "% Generated by scripts/build_dynamic_1m_table.py from raw event logs.",
        r"\begin{table*}[t]", r"\centering", r"\scriptsize",
        r"\caption{Large-scale dynamic-index validation at 1M final vectors under a 0.95 Recall@10 floor. Feasible means the held-out validation mean meets the floor; test Recall@10 is then reported without reselection. The base corpus contains 800k vectors and five update rounds insert 40k vectors each. Shifted and shuffled orders share final membership, update vectors, query identities, and checkpoints. $C$ excludes initial build; $C{+}V$ additionally charges validation-budget queries. An asterisk marks the largest measured budget when the floor is infeasible; -- denotes an unrecorded size for that infeasible run. CONDA rows use its fixed native $L_s=100$ and aggregate 128-query batch timing, so Q95 is not inferred.}",
        r"\label{tab:large_scale_dynamic_index_full}",
        r"\begin{tabular}{llcccccccccc}", r"\toprule",
        r"Order & Method & Budget & Feasible & Test R@10 & Worst R@10 & Q95 ms & Insert ms & Maint. ms & $C$ ms & $C{+}V$ ms & Index size \\",
        r"\midrule",
    ]
    for oi, cond in enumerate(order):
        if oi: lines.append(r"\midrule")
        for policy in policies:
            pairs = groups[(cond, policy)]
            ss = [s for _, s in pairs]
            feasible = all(s.get("feasible", False) for s in ss)
            if not feasible:
                # Report the maximum measured budget even when the floor is infeasible.
                max_budget = {"ivf_fixed": 128, "ivf_rebuilt": 128, "hnsw": 256}[policy]
                max_rows = []
                for r, _ in pairs:
                    erows = [e["budgets"][str(max_budget)] for e in r["events"]]
                    max_rows.append({
                        "test_recall": float(np.mean([e["test_recall"] for e in erows])),
                        "worst_recall": float(min(e["test_recall"] for e in erows)),
                        "query_p95_ms": float(np.mean([e["query_p95_ms"] for e in erows])),
                        "insert_ms": float(sum(e["insert_ms"] for e in r["events"])),
                        "maintenance_ms": float(sum(e["rebuild_ms"] for e in r["events"])),
                        "C_ms": float(sum(e["budgets"][str(max_budget)]["query_mean_ms"] * 64 + e["insert_ms"] + e["rebuild_ms"] for e in r["events"])),
                        "C_plus_V_ms": float(sum(e["budgets"][str(max_budget)]["query_mean_ms"] * 128 + e["insert_ms"] + e["rebuild_ms"] for e in r["events"])),
                    })
                means = {k: float(np.mean([z[k] for z in max_rows])) for k in max_rows[0]}
                vals = [cond, names[policy], f"{max_budget}*", "No", fmt(means["test_recall"], 4),
                        fmt(means["worst_recall"], 4), fmt(means["query_p95_ms"], 3), fmt(means["insert_ms"]),
                        fmt(means["maintenance_ms"]), fmt(means["C_ms"]), fmt(means["C_plus_V_ms"],), "--"]
            else:
                keys = ["budget", "test_recall", "worst_recall", "query_p95_ms", "insert_ms", "maintenance_ms", "C_ms", "C_plus_V_ms", "index_size_bytes"]
                means = {k: float(np.mean([s[k] for s in ss])) for k in keys}
                vals = [cond, names[policy], str(int(means["budget"])), "Yes", fmt(means["test_recall"], 4),
                        fmt(means["worst_recall"], 4), fmt(means["query_p95_ms"], 3), fmt(means["insert_ms"]),
                        fmt(means["maintenance_ms"]), fmt(means["C_ms"]), fmt(means["C_plus_V_ms"]),
                        f"{means['index_size_bytes']/1e6:.1f}M"]
            lines.append(" & ".join(vals) + r" \\")
    # Native CONDA is scored at its fixed L_s=100 endpoint.  Its C++ runner
    # reports one aggregate BatchSearch duration per checkpoint, so p95 and
    # index-size fields remain explicitly unavailable rather than estimated.
    conda_dir = ROOT / "results/native_dynamic_v1"
    for cond in order:
        path = conda_dir / f"conda_{cond}_detailed_summary.json"
        if not path.exists():
            continue
        summary = json.loads(path.read_text())
        c_ms = float(summary["insert_ms"] + sum(r["query_batch_ms"] for r in summary["rows"]))
        lines.append(" & ".join([
            cond, "CONDA-native", "100*", "No", fmt(summary["test_recall_mean"], 4),
            fmt(summary["worst_round_test_recall"], 4), "--", fmt(summary["insert_ms"]),
            "--", fmt(c_ms), fmt(c_ms), "--"
        ]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    OUT.write_text("\n".join(lines))
    print(OUT)


if __name__ == "__main__":
    main()
